sudo: required
services:
  - docker

before_install:
  - docker build -t gamemaniaz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gamemaniaz/react-test npm test -- --coverage

after_success:
  - docker build -t gamemaniaz/multi-client ./client
  - docker build -t gamemaniaz/multi-nginx ./nginx
  - docker build -t gamemaniaz/multi-server ./server 
  - docker build -t gamemaniaz/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gamemaniaz/multi-client
  - docker push gamemaniaz/multi-nginx
  - docker push gamemaniaz/multi-server
  - docker push gamemaniaz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-150976937038
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY